/** Presentation copy lives outside the Markdown generated by the Obsidian sync. */
export interface Project {
  question: string;
  stack: string[];
}

export const projects: Record<string, Project> = {
  "whatwhale-nl2docker": {
    question: "Can a tiny model remember the Docker flags I keep forgetting?",
    stack: ["Docker", "llama.cpp", "LoRA"]
  },
  "image-search-system": {
    question: "What does it take to teach a search engine to see?",
    stack: ["CLIP", "Qdrant", "S3"]
  }
};

export const statusLabels = {
  active: "in progress",
  live: "live",
  paused: "on the back burner",
  done: "completed"
};

